# Test Automation Configuration

browser:
  headless: false
  baseUrl: 'http://172.16.0.171:8086/mdw_corepkgshiire-web/DenpyoApproval.do'
  viewport:
    width: 1535
    height: 1025
  args:
    - '--start-maximized'
    - '--disable-blink-features=AutomationControlled'

execution:
  actionTimeout: 30000
  navigationTimeout: 30000
  pageLoadWait: 1000
  stepDelay: 500
  stopOnFailure: false
  stopOnChildFailure: false
  maxRetries: 3

screenshots:
  enabled: true
  fullPage: true
  captureBeforeSubmit: true
  captureAfterSubmit: true
  captureOnFailure: true
  cleanupBeforeRun: true
  outputPath: ./screenshots
  failurePath: ./screenshots/failures

logging:
  level: info
  logFile: ./test-execution.log

# NEW: Test configuration paths
paths:
  # Base directory for test configurations (can be absolute or relative)
  testConfigRoot: 'D:\learn\automation_test\tests'
  
  # Subdirectories within testConfigRoot
  scenarios: 'scenarios'
  testLists: 'test-lists'
  
  # Alternative: Use relative paths from project root
  # testConfigRoot: '../test-configs'